---
- name: Create action to run after firewall comes up to clear all rules
  template:
    src: firewall/setup-firewall.service.j2
    dest: /etc/systemd/system/setup-firewall.service

- name: Setup firewall
  systemd:
    name: setup-firewall
    state: started
    enabled: true
    daemon_reload: true
