server:
  port: 8080
t2:
  feature:
    provision-real-clusters: true
    provision-cluster-limit: 5
  workspace:
    directory: /var/t2/workspace/  
  security:
    token:
      source: file  # options: file | static
      file: /var/t2/security-token
      static: null
    credential-file: /var/t2/credentials.properties
  