spring:
  main:
    banner-mode: "off"
server:
  error:
    include-stacktrace: never
t2:
  build:
    version: "@project.version@"
    timestamp: "@build-timestamp@"
    git-commit: "@git.commit.id.describe-short@"
  workspace:
    directory: /tmp/t2-workspace/  
  feature:
    provision-real-clusters: true
    provision-cluster-limit: 5
  security:
    token:
      source: static  # options: file | static
      file: null
      static: t2-secret-token
