---
- name: ensure epel is installed at the latest version
  yum:
    name: epel-release
    state: latest
- name: ensure ansible is installed at the latest version
  yum:
    name: ansible
    state: latest
