---
- name: ensure epel is installed at the latest version
  yum:
    name: epel-release
    state: latest

- name: Ensure WireGuard tools are installed
  package:
    name:
      - wireguard-tools
    state: present
