- name: Clean template directory
  file:
    path: /var/t2/templates/
    state: absent

- name: create template directory for t2
  file:
    path: /var/t2/templates/
    state: directory
    owner: t2
    group: t2
    mode: "770"

- name: copy templates 
  copy:
    src: ../../../../templates/
    dest: /var/t2/templates/
    owner: t2
    group: t2
    mode: "0440"

