---
- name: restart bind
  service: 
    name: bind9 
    state: restarted

- name: restart iptables
  shell: "iptables-restore /etc/iptables/rules.v4"

- name: restart wireguard
  service:
    name: "wg-quick@wg"
    state: restarted

- name: reboot
  reboot:    
