---
- hosts: all
  vars_prompt:

    - name: ionos_username
      prompt: Username in IONOS cloud
      private: no

    - name: ionos_password
      prompt: Password in IONOS cloud

    - name: gandi_api_token
      prompt: API token for Gandi DNS services

  tasks:

    - name: create credentials file
      copy:
        dest: /var/t2/credentials.properties
        content: "ionos_username = {{ ionos_username }}\nionos_password = {{ ionos_password }}\ngandi_api_token = {{ gandi_api_token }}"
        owner: t2
        group: t2
        mode: "0440"
