---
# Template changed resolv.conf - this will be copied into place by the configure_network service
- name: Create resolv.conf template
  template:
    src: network/resolv.conf.j2
    dest: /root/resolv.conf.template

- name: Create network config script
  template:
    src: network/networkconf.sh.j2
    dest: /root/networkconf.sh
    mode: 0755

- name: Create action to run after network comes up and add default route
  template:
    src: network/configure_network.service.j2
    dest: /etc/systemd/system/configure_network.service

- name: Create route for internet access
  systemd:
    name: configure_network
    state: started
    enabled: yes
    daemon_reload: yes

