---
- name: ensure caddy is installed at the latest version
  yum:
    name: caddy
    state: latest
  notify:
    - restart caddy
- name: copy config file
  copy:
    src: Caddyfile
    dest: /etc/caddy/caddy.conf
  notify:
    - restart caddy
- name: enable caddy
  service:
    name: caddy
    daemon_reload: yes    
    enabled: yes
