---
- hosts: nat
  roles:
  - nat
- hosts: protected
  roles:
  - protected
- hosts: orchestrators
  roles:
  - orchestrator
- hosts: nodes
  roles:
  - node
- hosts: orchestrators
  roles:
  - orchestrator_finalized
