---
- name: restart zookeeper operator
  service: name=stackable-zookeeper-operator-server state=restarted enabled=yes

- name: restart spark operator
  service: name=stackable-spark-operator-server state=restarted enabled=yes

- name: restart kafka operator
  service: name=stackable-kafka-operator-server state=restarted enabled=yes