---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure iptables-services is installed
  apt:
    name: iptables-persistent
    state: present

- name: Ensure iptables config is up-to-date
  copy:
    src: iptables
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
  notify: 
    - restart iptables

- name: Install & configure BIND (DNS)
  include: bind.yml

- name: Install & configure Wireguard (VPN)
  include: wireguard.yml

- name: Set authorized key for client
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_client_keys if ssh_client_keys is iterable else [] }}"




